import {Hajj, Umrah} from '../Enums';
export const Hajj_Umrah_Details = {
  [`${Hajj.QIRAN}`]: [
    'Ihram',
    "Performing the Welcome Tawaf and Sa'y",
    'Going to Mina from Makkah',
    'Going to Arafat from Mina',
    'Going to Muzdalifah from Arafat',
    'Proceeding to Mina from Muzdalifah',
    'Tawaf al-Ifadha in the Holy City of Makkah',
    'Returning to Mina from Makkah',
    'Farewell Tawaf in the Holy City of Makkah',
    'Departing for home',
  ],
  [`${Hajj.IFRAD}`]: [
    'Ihram',
    "Performing the Welcome Tawaf and Sa'y,",
    'Going to Mina from Makkah',
    'Going to Arafat from Mina',
    'Going to Muzdalifah from Arafat',
    'Proceeding to Mina from Muzdalifah',
    'Tawaf al-Ifadha in the Holy City of Makkah',
    'Returning to Mina from Makkah',
    'Farewell Tawaf in the Holy City of Makkah',
    'Departing for home',
  ],
  [`${Hajj.TAMATTU}`]: [
    'Ihram',
    "Performing the Welcome Tawaf and Sa'y,",
    'Ihram for Hajj al-Tamattu',
    'Going to Mina from Makkah',
    'Going to Arafat from Mina',
    'Going to Muzdalifah from Arafat',
    'Proceeding to Mina from Muzdalifah',
    'Tawaf al-Ifadha in the Holy City of Makkah',
    'Returning to Mina from Makkah',
    'Farewell Tawaf in the Holy City of Makkah',
    'Departing for home',
  ],
  [`${Umrah.MUDARAF}`]: [
    'Ihram',
    "Performing the Welcome Tawaf and Sa'y,",
    'Ihram for Hajj al-Tamattu',
    'Going to Mina from Makkah',
    'Going to Arafat from Mina',
    'Going to Muzdalifah from Arafat',
    'Proceeding to Mina from Muzdalifah',
    'Tawaf al-Ifadha in the Holy City of Makkah',
    'Returning to Mina from Makkah',
    'Farewell Tawaf in the Holy City of Makkah',
    'Departing for home',
  ],
  [`${Umrah.TAMMATU}`]: [
    'Ihram',
    "Performing the Welcome Tawaf and Sa'y,",
    'Ihram for Hajj al-Tamattu',
    'Going to Mina from Makkah',
    'Going to Arafat from Mina',
    'Going to Muzdalifah from Arafat',
    'Proceeding to Mina from Muzdalifah',
    'Tawaf al-Ifadha in the Holy City of Makkah',
    'Returning to Mina from Makkah',
    'Farewell Tawaf in the Holy City of Makkah',
    'Departing for home',
  ],
};
