// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('d:/Osama/HajjProjectHassan/node_modules/react');
var { Component } = React;
var ReactNative = require('d:/Osama/HajjProjectHassan/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('HajjProjectHassan', appParameters);
});
require('d:/Osama/HajjProjectHassan/index.js');